### ISSUE TITLE
Kursplanung - Semesterbeginn + -ende soll auch planbar sein

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#109]
Semesterbeginn und -ende sollte nicht ausgegraut werden und zum Semester dazu gehören

**Comment by felixkam93** [comment]
Also falls 
Start: 01.05 dann wird dieser Termin (normalerweise) nicht ausgegraut
Ende: 30.06 dann wird dieser Termin ausgegraut.
Meiner Meinung nach ist es Ansichtssache, ob das Enddatum noch im Semester liegt oder ob das Semester wenn der letzte Tag der 30.06 ist eher bis zum 01.07 geht...

beide Varianten machen keine arbeit, jedoch sollten wir uns auf eine festlegen

**Comment by NessiT** [comment]
Also bei mir würde es immer ausgegraut..
Im Interview mit JB hatte er immer gemeint, dass wenn er Anfang und Ende angibt diese Tage auch zum Semester dazu gehören. Manchmal will er auch am letzten Tag eine Klausur noch planen. Aus diesem Grund würde ich sagen, dass der letzte Tag noch weiß sein soll...nicht, dass er da verwirrt ist :-D
