### ISSUE TITLE
Mailto does not work correctly

### ISSUE THREAD

**Issue by fischermax** [WISEA12/frontend#11]
Has anyone an idea, why "mailto" only works if you're in the change mode?
I added the function in the docentFormCtrl.js here:
switch(formUsage) {
        case 'show':
            $scope.docent = docentInstance;
            $scope.docentFormHelper.formTitle = "Dozent anzeigen";
            $scope.docentFormHelper.showMode = true;
            $scope.docentFormHelper.editMode = false;
            $scope.docentFormHelper.createMode = false;
            $scope.docentFormHelper.disabled = true;
            $scope.docentFormHelper.validation = false;
            $scope.mailto = function (docent) {
                var link = "mailto:" + docent.email;
                window.location.href = link;
            };
            break;

In my understanding this should ensure that the mailto is active when you're in the show mode?!

look at the branch "mailto"

**Comment by fischermax** [comment]
@treyla @tarekauel @LarsTi @felixkam93 @michischeid @npartsch @NessiT 
Soll mailto mit Doppelclick oder einfachen Click funktionieren??

**Comment by fischermax** [comment]
S. Master: latest commit 72f5ad31a0

**Comment by michischeid** [comment]
fixed problem
