### ISSUE TITLE
Beim Verschieben eines Events im Kalender wird die Id nicht an das backend geschickt.

### ISSUE THREAD

**Issue by michischeid** [WISEA12/frontend#120]
Beim Verschieben eines Events im Kalender wird die Id nicht an das backend geschickt. Dadurch gibt es eine Kollision mit sich selbst

**Comment by felixkam93** [comment]
![image](https://cloud.githubusercontent.com/assets/5337941/7170348/b60da34c-e3cd-11e4-915c-1e4c15cbace8.png)

hmm also semesterPlanning.ctrl.js
Zeile 112
Zeile 159

da wird die ID übergeben...

**Comment by felixkam93** [comment]
@michischeid

**Comment by LarsTi** [comment]
fixed in master
