### ISSUE TITLE
Nicht soooo wichtig!    Semesterplanung - Änderung bestehendes Event 

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#128]
Wenn ich ein bestehendes Event ändere und Wiederholungen angebe wird nur das Event auf das erste gewünscht Datum geändert aber keine Wiederholungen übernommen

Für Demo aber nicht wchtig :D

**Comment by felixkam93** [comment]
Du meinst dass eine Serie von Events geändert werden kann?
Auch hier wieder ... das war zu komplex...

**Comment by michischeid** [comment]
wir haben uns darauf geeinigt keine Serien zu ändern
