### ISSUE TITLE
Beim Löschen voN Events

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#129]
vielleicht auch die möglichkeit zu sagen, dass alle wiederholung von events ebenfalls gelöscht werden sollen....nicht nur 1 event

**Comment by felixkam93** [comment]
Eine solche Funktionalität wurde aus Komplexitätsgründen vorerst ausgeschlossen ;-)

**Comment by michischeid** [comment]
Wir haben uns darauf geeinigt keine Serien zu bearbeiten, löschen
