### ISSUE TITLE
Generierte PDF (Kalender) verschönern

### ISSUE THREAD

**Issue by treyla** [WISEA12/frontend#130]
Was ich bisher gesehen habe, sah ja nicht so prickelnd aus. Hab hier mal einen Schnappschuss von dem PDF der anderen Gruppe erhascht:

![img_20150414_133912](https://cloud.githubusercontent.com/assets/4633382/7155025/ab7cd49c-e35b-11e4-8260-1ea2e776f141.jpg)

**Comment by LarsTi** [comment]
[Issue im Backend](https://github.com/WISEA12/backend/issues/190)
