### ISSUE TITLE
Überschneidung Vorlesungen stimmt nicht.

### ISSUE THREAD

**Issue by bockndi** [WISEA12/frontend#135]
![imag3182](https://cloud.githubusercontent.com/assets/11404572/7166687/a7d3af1a-e3af-11e4-8b56-8d59d13d66ab.jpg)

Hab mal ein Bild angehängt. Hoffe ich bin im Frontend richtig. Es handelt sich um unterschiedliche Kurse, unt. Dozenten, unt. Räume. Nur die Uhrzeit überschneidet sich. Ist aber ja nicht schlimm.
Vorlesung müsste ohne Kollision anzulegen sein.

**Comment by LarsTi** [comment]
fixed in [pull request](https://github.com/WISEA12/backend/pull/201)
