### ISSUE TITLE
Darstellung Module in Modulplan

### ISSUE THREAD

**Issue by bockndi** [WISEA12/frontend#136]
@treyla : Kann man hier evtl. noch was machen? Bei vielen Vorlesungen in einem Modul sieht das dann so aus. Danke dir!
![imag3184 1](https://cloud.githubusercontent.com/assets/11404572/7166780/3cf9d704-e3b0-11e4-92d0-430a7cd3a580.jpg)

**Comment by bockndi** [comment]
edit: Und komischerweise wurden gleiche Module beim Bearbeiten eines Moduls noch mal angelegt, so dass dann z.B 2 mal Mathe auftaucht.

**Comment by michischeid** [comment]
um das Duplizieren kümmere ich mich

**Comment by treyla** [comment]
Ich bin für meinen Teil fertig.

**Comment by michischeid** [comment]
@bockndi Ich kann das Duplizieren nicht nachvollziehen. Bitte nochmal testen.

**Comment by bockndi** [comment]
Ich auch nicht. Sonst hätte ich es näher beschrieben. Ist die letzten Stunden aber auch nicht mehr aufgetreten.

Ich kann auch keine Module löschen, die ich gerade erst in den Modulplan angelegt habe. Sind noch nicht in der Planung verwendet. So lassen sich Fehler bei der Eingabe nicht korrigieren. 
Komplette Modulpläne sollte man nicht löschen dürfen, so lange Module nicht verwendet werden bei der Planung wäre es gut, wenn man diese noch entfernen könnte. 
Die doppelten bekomme ich auch nicht mehr weg.

**Comment by LarsTi** [comment]
@michischeid ich glaube das duplizieren kommt aus dem backend und ist gleich mit dem Problem [hier](https://github.com/WISEA12/backend/issues/204)
