### ISSUE TITLE
Event als Klausur

### ISSUE THREAD

**Issue by LarsTi** [WISEA12/frontend#137]
Wenn ein event eine Klausur ist (isExam flag) wird es grün angezeigt, wenn ich das event änder, wird der button allerdings in dem änderungsbildschirm nicht richtig gesetzt (steht trotz grüner farbe und klausurtermin im popup ist als nein gekennzeichnet)

**Comment by felixkam93** [comment]
https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/CHANGELOG.md#030-alpha1-2014-02-22
read only nur mit neuester verison anscheinend möglich
dazu ist eventuell ein bootstrap update notwendig ... könnte das folgen für andere komponenten haben?

**Comment by michischeid** [comment]
muss getestet werden

**Comment by michischeid** [comment]
fixed
