### ISSUE TITLE
csv Export

### ISSUE THREAD

**Issue by LarsTi** [WISEA12/frontend#138]
Sacramentorealestatetransactions.csv

a) ist der Name falsch,
b) der Inhalt passt gar nicht.

sprecht ihr da noch das mockup an?

**Comment by felixkam93** [comment]
haha das ist nur ein beispiel ;-)
wenn ihr uns einen (funktionierenden) Link zur verfügung stellt, dann immer man her damit und ich bau ihn ein! @LarsTi @danielhartmann

**Comment by LarsTi** [comment]
@felixkam93 
/api/event/export
sollte eigentlich gehen

**Comment by felixkam93** [comment]
@LarsTi 
was genau liefert diese csv?
im frontend wird sie nämlich unter 
Alle Termine für dieses Semester angegeben ... sieht nicht danach aus als ob die csv das liefert.
Whsl eher alle Termine des VVS als .csv für Group-E ausgeben?!

**Comment by LarsTi** [comment]
jope, sind alle events

Am 17. April 2015 um 19:04 schrieb felixkam93 <notifications@github.com>:
