### ISSUE TITLE
falsche Kollision besteht immer noch

### ISSUE THREAD

**Issue by bockndi** [WISEA12/frontend#144]
Der Fehler von gestern taucht immer noch auf. Man will Web-Prog anlegen und es kollidiert mit BWL. 
Anderer Kurs, anderer Dozent, anderer Raum, andere Vorlesung. Gleiche Zeit.

@michischeid : Wäre es noch möglich bei der Kollisionsmeldung anzugeben mit welchem Kurs es sich überschneidet? Bei vielen Kursen könnte das sehr hilfreich sein den Fehler zu finden.
Merci

**Comment by LarsTi** [comment]
die Kollision betrifft @felixkam93 und mich.

was ist denn der kollisions grund?
weil ich habs grade auch auf dem server ausprobiert und nit provozieren können

**Comment by bockndi** [comment]
![imag3185 1](https://cloud.githubusercontent.com/assets/11404572/7184227/684775ae-e45c-11e4-851c-2ee70f7e7a55.jpg)

Und eben trat noch ein Fehler auf. Im gleichen Kurs kann man ohne Fehler eine Vorlesung anlegen, die eine andere überdeckt.

![imag3186 6](https://cloud.githubusercontent.com/assets/11404572/7184279/c45788e8-e45c-11e4-8e53-80f70f16f4f8.jpg)

**Comment by LarsTi** [comment]
@felixkam93 es würde helfen, wenn man weiß, welches true/false flag zu welcher eigenschaft gehört

**Comment by LarsTi** [comment]
@bockndi @NessiT 
Bitte noch mal auf herz und nieren prüfen

**Comment by felixkam93** [comment]
@bockndi kann sein, dass die kollisionen richtig sind weil der Dozent in anderen Kursen einen Termin hat zu genau dem Zeitpunkt ...

**Comment by LarsTi** [comment]
Ihr Problem war ein echter bug (Cypher sucks) aber der sollte gefixed sein,
in den neueren Versionen.

Am 17. April 2015 um 15:11 schrieb felixkam93 <notifications@github.com>:

**Comment by NessiT** [comment]
meiner Meinung nach ist es behoben...hab alles mögliche getestet und System hat richtig reagiert

**Comment by NessiT** [comment]
Das ganze sieht jetzt so aus:
![unbenannt](https://cloud.githubusercontent.com/assets/11404573/7209449/f450a5e2-e548-11e4-8f69-70d2760e23e4.PNG)

Fehlt also warum überhaupt ein Problem entstanden ist

**Comment by LarsTi** [comment]
sollte eigentlich gefixed sein

**Comment by NessiT** [comment]
meiner Meinung nach ist es behoben...hab alles mögliche getestet und System hat richtig reagiert
