### ISSUE TITLE
Eventuelles Problem mit autocomplete --> TESTEN

### ISSUE THREAD

**Issue by fischermax** [WISEA12/frontend#146]
@bockndi @NessiT @michischeid @npartsch @felixkam93 @treyla 

Testet bitte mal bei euch, ob die Vorlesung "Investition und Finazierung" durhc die ng-tags/ autocomplete geladen werden. Bei mir nicht.....

Neues Modul "Finanzierung und Rechnungswesen" --> Vorlesung "Investition und Finanzierung" sowie "Bilanzierung"

letzteres wird mir durch auto complete angezeigt. "Investition und Finazierung" ist in den Vorlesungen enhalten

**Comment by fischermax** [comment]
ebenso:
Vorlesung laut autocomplete "ABWL5/ Unternehmensf" --> Fehlermeldung "lecture not found", obwohl diese auch in den Vorlesungen angezeigt wird

**Comment by LarsTi** [comment]
bekanntes problem (bitte alle davon suchen) 
-> Auf der DB existiert die lecture mit shorttitle ' abc' und im programm wird aus ' abc' 'abc' gemacht, deswegen funktioniert die Abfrage nicht, da halt das führende Leerzeichen bei uns gekillt wird..
-> DB import müsste korrigiert werden
-> Die Tester arbeiten auf einer (weitest gehend) korrigierten Datenfassung.

**Comment by michischeid** [comment]
neue DBDaten-Version benutzen
