### ISSUE TITLE
PDF exports

### ISSUE THREAD

**Issue by LarsTi** [WISEA12/frontend#148]
Ansprache der neuen schnittstelle für die planungskalender der Dozenten
(Buttons)

**Comment by felixkam93** [comment]
Hiermit ist ein Export eines PDF Files gemeint, welches <b>alle</b>  Events <b>eines</b> Dozenten darstellt. Meiner Meinung nach gehört das aus inhaltlicher Sicht nicht mehr zur Semesterplanung dh zum Kalendar. Sollte ein solcher Export Button in den Eigenschaften oder Tiles der Dozentenverwaltung eingepflegt werden? 
Darüber hinaus lässt die Schnittstelle zu, dass man einen Zeitraum angeben kann. Das PDF wird aber sehr unübersichtlich wenn bspw 1 Jahr angegeben wird. Deshalb kam der Vorschlag, dass das Startdatum immer "today" ist und das Enddatum "today + 3 Monate". Das Startdatum sollte meiner Meinung nach frei wählbar sein.
@NessiT @bockndi @LarsTi @treyla @michischeid

**Comment by LarsTi** [comment]
Naja, man kann auch start des monats und dann 3 monate machen
(Hintergrund: die wenigsten planen vom 23.7 bis 23.10, sondern eher vom 1.8 - 1.11 oder 1.7 - 1.10)
einfach um ein wenig usability zu kriegen

**Comment by michischeid** [comment]
Ich denke, dass sämtliche Exports auf der Kalenderansicht angeboten werden sollen, da es ja in jedem Fall um konkrete Events geht (auch wenn es kursübergreifend ist). Vielleicht kann man den Dozentenplanexport-Button in die nähe des Buttons zum hinzufügen eines Dozenten zum Kalender machen. Ich würde Start- und Enddatum flexibel halten, aber mit einer Vorauswahl belegen.@NessiT @bockndi @LarsTi @treyla @michischeid @felixkam93

**Comment by felixkam93** [comment]
Alles klar habe da schon so etwas im Kopf gehabt. 
@danielhartmann wie verhält sich das PDF wenn der Zeitraum wesentlich länger wird als 12 Wochen?

**Comment by felixkam93** [comment]
Done 
Bitte prüfen @NessiT @bockndi
