### ISSUE TITLE
geplante Objekte sollte man nicht löschen können

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#149]
Wenn ich einen Dozenten/ Vorlesung geplant habe und danach löschen will, bekomme ich keine Meldung, dass er noch verwendet wird...vielleicht kann man da auch noch ne Kollision oder so einbauen

**Comment by felixkam93** [comment]
das ist (zum Glück) Sache des Backends
@NessiT @tarekauel

**Comment by felixkam93** [comment]
okay fairerweise: teilweise Sache des Backends

**Comment by LarsTi** [comment]
nicht ganz klar, was gemeint ist?
also ich habe eine vorlesung geplant und lösche die wieder..
warum sollte ich da ne kollision anzeigen?
so nach dem motto: Hey, dein dozent hat da übrigens immer noch ein event für den zeitraum?

**Comment by NessiT** [comment]
Es geht eher darum, dass man einen Dozent nicht löschen kann, wenn er noch für ein Event ausgewählt ist...

**Comment by LarsTi** [comment]
achso, ja, das backend sagt da (momentan) nur bescheid, dass noch assoziationen existieren.
müsste halt mal definiert werden, was da noch kommen soll.. aber keine Ahnung, wie toll das wird, wenn ich sage, der ist noch mit 500 events verknüpft (geschweige denn, wenn die alle aufgelistet sind.)

**Comment by NessiT** [comment]
Ok dann lassen wir das einfach so...löschen ja eh Nichts wie man am alten System sieht  :-D
