### ISSUE TITLE
Semesterplanung - Vorschlagsliste bei Kurs

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#150]
Vorschlagsliste zeigt alle Kurse an auch wenn ich schon was angegeben habe...der gewollte kurs kommt weiter unten und dick...kann man das vielleicht wie bei den anderen Listen machen?

**Comment by felixkam93** [comment]
Ich weiß ehrlich gesagt nicht was/wo du meinst, dass ich einen Kurs auswählen kann

**Comment by NessiT** [comment]
Kursraum meine ich..tut mir leid

**Comment by felixkam93** [comment]
fixed ;) aber ist noch nicht im Master
