### ISSUE TITLE
Balken für geplante Vorlesungen nicht gefüllt

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#158]
Hab jetzt einen weißen Balken, obwohl ich für die Vorlesung Stunden geplant habe...bei der Planung wird mir aber auch nicht angezigt wie viele Stunden insgesamt geplant werden sollen...
So sieht das Ganze aus:
![unbenannt](https://cloud.githubusercontent.com/assets/11404573/7215954/21279180-e5ed-11e4-956b-0a1033b51e88.PNG)

**Comment by felixkam93** [comment]
ich hab den balken auch schon mal hin und wieder bekommen ... kannst du ungefähr sagen, wenn er auftritt oder ist das eher so random mäßig? tritt der auf wenn immer 100% geplant wurden oder soger 110% dh. mehr stunden als nötig?

**Comment by NessiT** [comment]
Ist eher random..hab ihn weiß gehabt dann wieder grün...der weiße kam glaub ich als ich ein Event mal gelöscht hatte..aber ist auch schon grün geblieben als ich was gelöscht hab

**Comment by LarsTi** [comment]
habs gerade gehabt, dass der weiß geworden ist beim planen aus der monatsübersicht..
beim neu laden des kalenders (erneut über semesterplanung) war dann wieder alles so wie es soll..
vllt werden beim bearbeiten aus der monatssicht irgendwelche werte nicht richtig berechnet/gesetzt

**Comment by felixkam93** [comment]
Bin mir fast sicher, dass es etwas damit zu tun hat, dass obwohl der "show" Mode aktiv ist, etwas an den openHours gedreht wird und deshalb die progress bar ausrastet @michischeid 
![image](https://cloud.githubusercontent.com/assets/5337941/7216950/d8b2d54c-e612-11e4-8560-4ac34394d81d.png)

**Comment by michischeid** [comment]
@felixkam93 @NessiT @LarsTi  Bitte nochmal testen. sollte gefixed sein.

**Comment by LarsTi** [comment]
was hab ich damit zu tun?

**Comment by michischeid** [comment]
@LarsTi du bist zufällig die Person, die es möglich machen kann, dass die analyse die neue Version testen kann :-)
