### ISSUE TITLE
PDF in Kombi mit Kalender Semesterranfang/ ende

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#159]
Der Semesteranfang und das -ende ist im Moment ausgegraut, aber trotzdem beplanbar...jedoch werden Vorlesungen im PDF nicht angezeigt, sondern die Tage immer als frei gekennzeichnet

**Comment by felixkam93** [comment]
Ist kein Problem des Frontends sondern des Backends.
ausgegraut werden bei uns die Felder nicht mehr. Aber so wie bei mir auch könnte ich mir vorstellen dass der Range im Backend das Anfangs und Enddatum nicht inkludiert
