### ISSUE TITLE
Kollision 

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#160]
Kollision, weil der Dozent schon einen Termin hat, obwohl bei der anderen Vorlesung noch keinen Dozenten besitzt:

![unbenannt](https://cloud.githubusercontent.com/assets/11404573/7216138/6ee744b8-e5f4-11e4-9284-ba6e2e141146.PNG)

**Comment by LarsTi** [comment]
Kann es sein, dass du ein Event mit Baumgart erstellt hast, den Dozenten wieder gelöscht hast und dann die Kollision auftritt?

**Comment by LarsTi** [comment]
Ich habs mir nämlich kurz angeschaut, der Dozent ist definitiv beiden Events zugeordnet (Das nur in einem event das angezeigt wird ist nen fehler, jo) 
@felixkam93

**Comment by LarsTi** [comment]
PS:
Backend antwort:

{"validEvents":[],"collidingEvents":[{"eventOfCollection":{"id":31,"start":"2015-04-24T07:30:00.000Z","end":"2015-04-24T08:30:00.000Z","lecture":{"title":"Einführung in die Programmierung","shortTitle":"Prog I"},"docent":{"studyProgramManager":true,"state":{"start":"2015-05-23T08:00:00.000Z","plannedHours":2.3333333333333335,"end":"2015-05-23T10:30:00.000Z","pause":5,"title":"Prog I \nBaumgart \n069C","id":37},"title":"Prof. Dr.-Ing.","street":"Langgässerweg 4","firstName":"Jörg","lastName":"Baumgart","sex":"m","zipCode":"64285","phonePrivate":"06151 61327","city":"Darmstadt","id":21,"lectures":[{"title":"Einführung in die Programmierung","shortTitle":"Prog I"}]},"pause":5,"title":"Prog I \nBaumgart \n069C","semester":{"endDate":"2015-06-12T22:00:00.000Z","startDate":"2015-04-13T10:58:33.973Z","number":1,"id":1,"lecture":[],"hours":10},"room":{"name":"069C","number":"069C","id":2}},"collidingEvents":[{"reason":{"docent":true,"room":false,"course":false,"publicHoliday":false},"event":{"start":"2015-04-24T07:30:00.000Z","end":"2015-04-24T09:30:00.000Z","pause":15,"title":"Prog I \n \n255B","id":351,"semester":{"endDate":"2015-05-14T22:00:00.000Z","startDate":"2015-04-15T18:19:58.772Z","number":1,"id":7,"lecture":[],"hours":35},"lecture":{"title":"Einführung in die Programmierung","shortTitle":"Prog I"},"docent":{"studyProgramManager":true,"state":{"start":"2015-05-23T08:00:00.000Z","plannedHours":2.3333333333333335,"end":"2015-05-23T10:30:00.000Z","pause":5,"title":"Prog I \nBaumgart \n069C","id":37},"title":"Prof. Dr.-Ing.","street":"Langgässerweg 4","firstName":"Jörg","lastName":"Baumgart","sex":"m","zipCode":"64285","phonePrivate":"06151 61327","city":"Darmstadt","id":21,"lectures":[{"title":"Einführung in die Programmierung","shortTitle":"Prog I"}]},"room":{"name":"255B","number":"255B","id":9}}}]}]}

**Comment by felixkam93** [comment]
ey keine adressen von dozenten auf github!!!! @LarsTi

**Comment by LarsTi** [comment]
Sry, mein Fehler, danke fürs löschen

**Comment by felixkam93** [comment]
@NessiT kannst du kurz erklären wie du das erzeugt hast?

**Comment by felixkam93** [comment]
Folgendes, nachdem Lars mir die datenbank geschickt habe, konnte ich feststellen, dass Kurs WWI12SCA am 24.04 einen Termin hat. Der Titel des Events wird momentan nicht richtig angezeigt. Jedoch wird auf das Event geklickt ist der Dozent "JB" gepflegt. Der fehlerhafte Titel ist Ursprung einer älteren Version. Kann es sein dass das Event "damals" mit der alten Version erstellt wurde?

Ein Ändern des Events, obwohl es eine Kollision hat sollte den Titel verbessern und den Dozenten wieder anzeigen. Daraufhin wird in der Kollision auch der Dozent wieder angezeigt.
