### ISSUE TITLE
Fehlertext auf Englisch

### ISSUE THREAD

**Issue by bockndi** [WISEA12/frontend#162]
https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xpf1/v/t35.0-12/11154223_945583632159544_1652655006_o.jpg?oh=67bbd421b541e21c744deb6e5bde3242&oe=5535F429&__gda__=1429535353_36e34660c1e6120317ef3e57132dafc7

Einsendung von David: Besteht Möglichkeit Fehlertext auf Deutsch darzustellen?
Merci.

**Comment by michischeid** [comment]
Bitte Fehlertexte überarbeiten @LarsTi  oder @tarekauel

**Comment by LarsTi** [comment]
warum tarek und ich?
ist ja nicht so, als hätte ich als einserkandidat nicht vielleicht was anderes zu tun :ironie:
Außerdem könnte das genauso gut @danielhartmann 
Aber vielen lieben dank, dass sowas erstmal bei mir landen.. :rage:

**Comment by LarsTi** [comment]
https://github.com/WISEA12/backend/pull/235
