### ISSUE TITLE
collision detection for holidays and docents

### ISSUE THREAD

**Issue by michischeid** [WISEA12/frontend#20]
includes a popup for collisions coming up

**Comment by michischeid** [comment]
What would you think about a collision API like

GET api/eventCollisions?start="2015-08-31T16:47+00:00" end="2015-08-31T18:47+00:00"
returns: eventsArray

or

GET api/eventCollisions?events="eventsArray"
returns: eventsArray

?

**Comment by felixkam93** [comment]
brauchen wir eine API hierbei? ich dachte das macht das frontend selbst? indem bei jedem anlegen/update die eventSources Objekte durchsucht werden... kann natürlich mit steigendem semester zu erheblichen performance probleme kommen ... 
falls eine api benötigt wird dann muss diese auch den kurs kennen denke ich, damit nicht event kollisionen mit anderen kursen untersucht werden.
deshalb denke ich dass variante zwei die bessere ist.
Wann wird diese überprüfung überhaupt durchgeführt?
Prüft das Backend beim anlegen bzw update nicht auf kollision?

**Comment by michischeid** [comment]
should be done
