### ISSUE TITLE
support and render different calender sources like holidays and docentEvents 

### ISSUE THREAD

**Issue by michischeid** [WISEA12/frontend#22]

**Comment by felixkam93** [comment]
Was passiert, wenn der Dozent Max Mustermann zweifach existiert, was möglich ist, da zwei Personen den gleichen Namen besitzen können.

**Comment by felixkam93** [comment]
JSON Object für Public Holiday Events:

{id: 1, title: "Ostermontag", start: new Date(y,3, 6, 12 , 0),room:"", docent:"", allDay: true, className:"publicHoliday", editable: false},

**Comment by felixkam93** [comment]
JSON Object zum Anzeigen zusätzlicher Terminer einzelner Dozenten:

 {id: 1, title: "additionalDocent", start: new Date(y,m, 22, 12 , 0), end: new Date(y, m, 22, 14, 0), allDay: false, editable: false, description: 'first description', docent: 'Herr Baumgart', room: "240B", className:"addDocentCalendar"},
