### ISSUE TITLE
Geplante Stunden Kalkulation 

### ISSUE THREAD

**Issue by felixkam93** [WISEA12/frontend#24]
Lege ich einzeln Events derselben Vorlesung an, wird nicht heraus gefunden, ob bereits Events zu dieser Vorlesung angelegt wurden und wie viele Stunden hierdurch bereits verplant wurden

**Comment by michischeid** [comment]
baue ich noch ein

**Comment by michischeid** [comment]
kann erst fertig gestellt werden, wenn wir den object austausch programmiert haben

**Comment by michischeid** [comment]
done

**Comment by felixkam93** [comment]
Berechnung funktioniert noch nicht 100%

![image](https://cloud.githubusercontent.com/assets/5337941/6886297/4752a27e-d638-11e4-97b4-19f006ac8546.png)

Dazu: Wenn ein event angeklickt wird zum ändern aber nichts geändert wird, lässt es sich nicht über den schließen button schließen. Bei ESC ändern sich die planned hours obwohl sie es nicht sollten.

**Comment by michischeid** [comment]
fixed
