### ISSUE TITLE
Pflichtfelder beim Anlegen eines Moduls anzeigen/makieren

### ISSUE THREAD

**Issue by felixkam93** [WISEA12/frontend#36]

**Comment by fischermax** [comment]
@treyla  wie hast du die rote Umrandung hinbekommen, wenn ein Pflichtfeld leer ist? mit ner speziellen CSS??

**Comment by michischeid** [comment]
Habe ich eingebaut

**Comment by fischermax** [comment]
wo hast du das eingebaut?? meine letzte änderung war ja die anzeige "pflichtfeld"
