### ISSUE TITLE
Wie soll der Kalender dargestellt werden

### ISSUE THREAD

**Issue by felixkam93** [WISEA12/frontend#46]
5-Tage Woche sprich Montag bis Freitag?
Hat den Vorteil, dass wir mehr Platz in der Breite haben.
![nurarbeitswoche](https://cloud.githubusercontent.com/assets/5337941/6853243/452a1b8a-d3ea-11e4-9c4e-5ec97b597228.jpg)

Montag - Samstag, da es auch Vorlesungen am Samstag geben kann

![arbeitswoche samstag](https://cloud.githubusercontent.com/assets/5337941/6853242/4528ddce-d3ea-11e4-96d5-9db5d4a8e3d4.jpg)

7-Tage Woche, der Vorteil hierbei ist meiner Meinung nach, dass alle Feiertage angezeigt werden und "man es so gewohnt ist"

![7tagewoche](https://cloud.githubusercontent.com/assets/5337941/6853244/452c775e-d3ea-11e4-89f0-6c9a9a5657e8.jpg)

**Comment by LarsTi** [comment]
Finde die 6tage Version gut..

**Comment by michischeid** [comment]
Sehe ich auch so. 6 Tage

**Comment by treyla** [comment]
Wäre auch für die 6-Tage-Ansicht.

**Comment by felixkam93** [comment]
okay 6 Tage Ansicht ist umgesetzt
