### ISSUE TITLE
Bearbeitungsbildschirm - "Abbrechen" Button

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#48]
Beim Bearbeiten von Dozent, Vorlesung und Raum erfüllt der Abbrechen-Button nicht die gewünschte Funktion. Wenn ich etwas ändere und dann auf Abbrechen klicke, werden trotzdem die Änderungen abgespeichert. Ich erwarte jedoch, dass beim Klicken auf den Abbrechen Button die Änderungen verworfen und nur beim Anlegen Button Änderungen übernommen werden.

**Comment by NessiT** [comment]
Bei Modul das gleiche Problem

**Comment by michischeid** [comment]
An denjenigen der das fixed: sollte mit eine Kopie des Objekts am Anfang (angular.copy) und einem Zurückschreiben beim Abbrechen gelöst sein.

**Comment by michischeid** [comment]
done
