### ISSUE TITLE
Module hinzufügen - Vorlesung

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#50]
Wenn ich Module einem Modulpan hinzufüge, müssen Vorlesungen angegeben werden.

Die Vorlesung wird nur wirklich eingetragen, wenn ich diese aus der Liste auswähle. Die Liste zeigt mir zwar, welche Vorlesung vom Schreiben her übereinstimmt, aber wird nicht ganz oben aufgelistet. Beim Drücken von Enter wird der 1. Eintrag genommen, der in meinem Fall überhaupt nicht übereinstimmt hat.
Entweder die Liste mit Vorschlägen so sortieren, dass die übereinstimmenden Vorlesungen ganz oben aufgeführt werden oder wirklich nur die Vorlesungen, welche übereinstimmen aufführen.

Nice to have: Wenn die Vorlesung richtig geschrieben wurde, sollten auch Stunden angegeben werden können. Im Moment muss man die Vorlesung immer aus der Liste auswählen.

**Comment by michischeid** [comment]
Vorschlagslistenproblem. Baue ich noch ein

**Comment by michischeid** [comment]
fixed
