### ISSUE TITLE
Kursplanung - Kurs anlegen nicht möglich

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#51]
Ich kann keinen Kurs anlegen, da kein Studiengangsleiter angegeben werden kann. Ich müsste ihn aus einer Liste auswählen, welche ich aber nicht angezeigt bekomme. Das richtig schreiben der Persons reicht nicht aus.

**Comment by npartsch** [comment]
bei mir funktioniert das anlegen eines kurses einwandfrei. hast du eventuell keinen studiengangsleiter erstellt? du musst mindestens einen dozent als studiengangsleiter markieren.
