### ISSUE TITLE
Zurück-Pfeil bei Kalender

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#57]
Bei Kalenderansicht ein Zurück-Pfeil einbauen...finde ich als User irgendwie angenehmer/notwendig

**Comment by felixkam93** [comment]
@NessiT ich gehe davon aus, dass der zurück pfeil zur Kursplanung zurückgehen soll richtig?

**Comment by NessiT** [comment]
Richtig

**Comment by felixkam93** [comment]
@NessiT soll ichs wieder schließen?
