### ISSUE TITLE
Kurs bearbeiten

### ISSUE THREAD

**Issue by NessiT** [WISEA12/frontend#58]
Beim Anlegen eines Kurses geb ich alle möglichen Infos ein, kann nachträglich aber nichts davon einsehen...ist das so gewollt? :-D

**Comment by michischeid** [comment]
In der Mitte oben, blau unterlegt, kannst du eigentlich die Detailansicht einsehen

**Comment by npartsch** [comment]
Wie Michael schon erwähnt hat, kann man die Detailansicht bei klicken auf den blau hinterlegten Kursnamen öfnnen.
