### ISSUE TITLE
Kursplanung

### ISSUE THREAD

**Issue by LarsTi** [WISEA12/frontend#60]
Kursplanung:
Wenn ich in einer Kachel auf ein hinzugefügtes Modul klicke, erscheint bei mir die Fehlermeldung "Fehler im Backend".
Danach werden auch alle eingefügten Module beim Neuladen aus der Kursplanung entfernt.

->Recherche: es werden 2 Puts gefeuert (einmal 500 und einmal 20X)
checked das mal ;)

**Comment by npartsch** [comment]
Ich kann die Fehlermeldung bei mir nicht nachvollziehen.
