### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by fischermax** [WISEA12/frontend#69]
Status durch Anzeige letzte Vorlesung ersetzen

**Comment by fischermax** [comment]
Neu, wenn keine letzten Vorlesungen vorhanden

**Comment by michischeid** [comment]
@LarsTi Können ihr im Backend bei GET docent die letzteVorlesung anhängen, falls es eine gibt?

**Comment by LarsTi** [comment]
Möglich ja, aber desto mehr infos ich zu einem docent ziehe, desto mehr callbacks brauch ich, die dann zum einen eure reihenfolge am frontend kaputt machen (orderBy müsste ich dann wieder syncen und so) und desto länger dauert der request (was das größere Problem ist).
Fazit:
Ja, aber auf kosten der performance. ist es euch das wert?

**Comment by michischeid** [comment]
@LarsTi, @tarekauel  Ich finde den Status, wie er jetzt implementiert ist ziemlich sinnlos. Daher würde ich schon für die Version mit der "letzten Vorlesung" plädieren. Ich denke gerade solche Anwendungsgebiete sind ein Grund warum wir uns am Anfang für die GraphDB entschieden haben, was wir deshalb auch als unseren Vorteil nutzen sollten. Wie groß sind denn die Performancenachteile?

**Comment by michischeid** [comment]
done #97
