### ISSUE TITLE
PUT lecture

### ISSUE THREAD

**Issue by fischermax** [WISEA12/frontend#7]
shortTitle should not be allowed to change --> unique identifier 
otherwise we get problems with the backend

**Comment by LarsTi** [comment]
backend simple wont accept a put on a specific lecture and changing the shortTitle in the json.
would lead to 400 - Bad Request

**Comment by felixkam93** [comment]
Ist dieses Issue eigentlich noch aktuell? Falls nein bitte schließen

**Comment by fischermax** [comment]
Ähm eigentlich ja. Nur mittlerweile gibts n 404. Im Frontend darf das Feld shortTitle nicht änderbar sein --> kümmer mich drum

**Comment by fischermax** [comment]
fixed
commit bef202e5d80ba0365f851e7a719db89e2b84577e
