### ISSUE TITLE
Suchfunktion nach Modul bei Kursplanung

### ISSUE THREAD

**Issue by fischermax** [WISEA12/frontend#77]
Wenn ich in der Kursplanung bspw. die Vorlesung "Mathematik für Wirtschaftsinformatiker" suche und "Mathe" in die Such leiste eingebe erscheint unter dem Reiter "Mathematische Grundlagen 1" die Vorlesung "Mathe für Wirtschaftsinformatiker" mti Kurztitel. Soweit ok
ABER wenn ich diese Vorlesung, dann ins erste Semester ziehe ist da nicht die gesuchte Vorlesung, sondern "Logik und Algebra", welche die 2. Vorlesung im Modul "Mathe grundlagen 1" bildet

Siehe auch Bild
![kursplanung2](https://cloud.githubusercontent.com/assets/8883870/6986127/9caed8f4-da3a-11e4-8789-a6e018d34c42.jpg)

**Comment by npartsch** [comment]
Der Fehler war für mich nur sehr schwer reproduzierbar. Der Fehler tritt jedoch bei mir aufn, wenn ich eine ganz merkwürde Reihenfolge von Schritten durchführe. 
1. Lecture in das Semester ziehen.
2. Dann nach dem Lecture im Modulplan suchen.
3. Dann die Lecture  wieder zurück in den Modulplan verschieben.
4. Dann den Kurs wieder zurück in das Semester ziehen. 

Wenn ich das richtig sehe ist hierbei der Fehler in der angular-ui-tree-lib und ich weiß gerade echt nicht was ich dagegen tuen kann :/

**Comment by fischermax** [comment]
ok, gerade gings wieder
