### ISSUE TITLE
Buttons bei collision Detection ggf. Verschönern 

### ISSUE THREAD

**Issue by michischeid** [WISEA12/frontend#78]
Buttons bei collision Rezeption ggf. Verschönern

**Comment by felixkam93** [comment]
more or less done ... still waiting for backend 
review in branch felixCalendar

**Comment by LarsTi** [comment]
Grund sollte noch besser aufgelistet werden, sonst kann hier denk ich mal geputzt werden :dancer:

**Comment by felixkam93** [comment]
Ich denke ist soweit geschehen
