### ISSUE TITLE
Modul anlegen

### ISSUE THREAD

**Issue by LarsTi** [WISEA12/frontend#83]
Vorlesung wird als required Field angezeigt, ist es aber offensichtlich nicht

**Comment by LarsTi** [comment]
Vorlesung kann hinzugefügt werden, obwohl bearbeiten modus nicht aktiv.

**Comment by michischeid** [comment]
Ist eigentlich gefixed

**Comment by npartsch** [comment]
Ich habe eigentlich vor ca einer Woche die ng-tags gefixt, das heißt im View-Modus können keine Vorlesungen hinzugefügt oder gelöscht werden. Ich habe mir das gerade nochmals angeschaut, das Issue ist für mich nicht ersichtlich.

**Comment by michischeid** [comment]
@LarsTi: Bitte erneut öffnen, wenn es doch nicht gelöst sein sollte
