### ISSUE TITLE
Code aufräumen

### ISSUE THREAD

**Issue by fischermax** [WISEA12/frontend#84]
Code bereinigen und evtl kommentieren

**Comment by LarsTi** [comment]
ich räum dann mal euren code auf..
NICHT :dash:

**Comment by fischermax** [comment]
@LarsTi  wollte dich nicht zuordnen

**Comment by michischeid** [comment]
@fischermax @felixkam93 @fischermax @npartsch @treyla Habt ihr euren Code (entsprechend der Bereiche für die ihr verantwortlich wart) aufgeräumt? (Kommentieren, auskommentierten Code löschen, nicht genutzte libs löschen, Variablenbennenungen refactoren...)

**Comment by michischeid** [comment]
https://www.jetbrains.com/webstorm/help/creating-jsdoc-comments.html

**Comment by michischeid** [comment]
ngDocs wäre zur Dokumentation nice gewesen. Wenn noch jemand lust hat :-)

**Comment by michischeid** [comment]
Ich bin fertig: modulePlanning und eventForm sind damit fertig.

**Comment by fischermax** [comment]
erledigt

**Comment by treyla** [comment]
done
