### ISSUE TITLE
Start und Ende des Semesters in Kalender ggf. hervorheben

### ISSUE THREAD

**Issue by michischeid** [WISEA12/frontend#91]
Events anlegen:
- Wenn man Events über das Ende des Semesters legt, sollte eine Warnung auftauchen, dass hier bereits Praxisphase ist

**Comment by felixkam93** [comment]
Es soll eine Warnung sein, so wie bspw wenn ein Bad Request vorgefallen ist?
Oder eher ein Pop-up das bestätigt werden muss?

**Comment by felixkam93** [comment]
Kalendertage die außerhalb des Semesters liegen werden nun in dunkel grau dargestellt.

**Comment by felixkam93** [comment]
@NessiT
