### ISSUE TITLE
Farben des Status beim Dozent

### ISSUE THREAD

**Issue by michischeid** [WISEA12/frontend#96]
Abhängig von der letzten gehaltenen Vorlesung eines Dozenten werden die Kacheln anders gefärbt.
@treyla Schau dir das bitte mal an. Vielleicht sind die Farben nicht optimal gewählt :-)

![image](https://cloud.githubusercontent.com/assets/5337937/7102560/dc64a380-e083-11e4-8b2d-c8550b7579f9.png)

**Comment by treyla** [comment]
Also ich persönlich finde die Idee gut, die Frage ist nur, ob der User auch auf Anhieb versteht, was mit den Farben gemeint ist. Auf den ersten Blick wirkt es überfordernd. Vielleicht sollte man eher auf die farbliche Kennzeichnung verzichten und stattdessen eine "Letzte Aktivität"-Information mit auf der Kachel anzeigen. Diese kann von mir aus farblich hervorgehoben werden. Entscheidung treffen wir in der Gruppe würde ich sagen.
